#define URQUAN_PMAP_ANIM "comm.urquan.graphics"
#define URQUAN_FONT "comm.urquan.font"
#define URQUAN_COLOR_MAP "comm.urquan.colortable"
#define URQUAN_CONVERSATION_PHRASES "comm.urquan.dialogue"
#define URQUAN_MUSIC "comm.urquan.music"
