#define BLACKURQ_PMAP_ANIM "comm.kohrah.graphics"
#define BLACKURQ_FONT "comm.kohrah.font"
#define BLACKURQ_COLOR_MAP "comm.kohrah.colortable"
#define BLACKURQ_CONVERSATION_PHRASES "comm.kohrah.dialogue"
#define BLACKURQ_MUSIC "comm.kohrah.music"
