#define UMGAH_PMAP_ANIM "comm.umgah.graphics"
#define UMGAH_FONT "comm.umgah.font"
#define UMGAH_COLOR_MAP "comm.umgah.colortable"
#define UMGAH_CONVERSATION_PHRASES "comm.umgah.dialogue"
#define UMGAH_MUSIC "comm.umgah.music"
