#define MELNORME_PMAP_ANIM "comm.melnorme.graphics"
#define MELNORME_FONT "comm.melnorme.font"
#define MELNORME_COLOR_MAP "comm.melnorme.colortable"
#define MELNORME_CONVERSATION_PHRASES "comm.melnorme.dialogue"
#define MELNORME_MUSIC "comm.melnorme.music"
