#define YEHAT_PMAP_ANIM "comm.yehat.graphics"
#define YEHAT_FONT "comm.yehat.font"
#define REBEL_CONVERSATION_PHRASES "comm.yehat.rebel.dialogue"
#define YEHAT_COLOR_MAP "comm.yehat.colortable"
#define YEHAT_CONVERSATION_PHRASES "comm.yehat.dialogue"
#define REBEL_MUSIC "comm.yehat.rebel.music"
#define YEHAT_MUSIC "comm.yehat.music"
