#define THRADD_PMAP_ANIM "comm.thraddash.graphics"
#define THRADD_FONT "comm.thraddash.font"
#define THRADD_COLOR_MAP "comm.thraddash.colortable"
#define THRADD_CONVERSATION_PHRASES "comm.thraddash.dialogue"
#define THRADD_MUSIC "comm.thraddash.music"
