// This string is autogenerated by ChangeAppSettings.sh, do not change spaces amount
package de.schwardtnet.alienblaster;

import android.app.Activity;
import android.content.Context;

class Globals {
	// This string is autogenerated by ChangeAppSettings.sh, do not change spaces amount
	public static String ApplicationName = "AlienBlaster";

	// Should be zip file
	// This string is autogenerated by ChangeAppSettings.sh, do not change spaces amount
	public static String DataDownloadUrl = "http://sites.google.com/site/xpelyax/Home/alienblaster110_data.zip?attredirects=0%26d=1"; // This string is autogenerated by ChangeAppSettings.sh, do not change spaces amount

	// Set DownloadToSdcard to true if your app data is bigger than 5 megabytes.
	// It will download app data to /sdcard/alienblaster then,
	// otherwise it will download it to /data/data/de.schwardtnet.alienblaster/files -
	// set this dir in jni/Android.mk in SDL_CURDIR_PATH
	// This string is autogenerated by ChangeAppSettings.sh, do not change spaces amount
	public static boolean DownloadToSdcard = false;
	
	// Set this value to true if you're planning to render 3D using OpenGL - it eats some GFX resources, so disabled for 2D
	public static boolean NeedDepthBuffer = false;
}

class LoadLibrary {
	public LoadLibrary()
	{
		System.loadLibrary("tremor");
		System.loadLibrary("sdl");
		System.loadLibrary("sdl_mixer");
		System.loadLibrary("sdl_image");
		System.loadLibrary("sdl_ttf");
	}
}
