#define ARILOU_COLOR_MAP "comm.arilou.colortable"
#define ARILOU_PMAP_ANIM "comm.arilou.graphics"
#define ARILOU_FONT "comm.arilou.font"
#define ARILOU_CONVERSATION_PHRASES "comm.arilou.dialogue"
#define ARILOU_MUSIC "comm.arilou.music"
