LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := physfs

APP_SUBDIRS := . archivers platform include

LOCAL_CFLAGS := -O2 -fsigned-char -Dphysfs_EXPORTS -D_REENTRANT -D_THREAD_SAFE -DHAVE_ASSERT_H=1 -DPHYSFS_SUPPORTS_ZIP=1 -DPHYSFS_SUPPORTS_GRP=1 -DPHYSFS_SUPPORTS_HOG=1 -DPHYSFS_SUPPORTS_MVL=1 -DPHYSFS_SUPPORTS_QPAK=1 -D_FILE_OFFSET_BITS=32 -D_LARGE_FILES -DPHYSFS_NO_CDROM_SUPPORT=1

LOCAL_CPP_EXTENSION := .cpp

LOCAL_C_INCLUDES := $(foreach F, $(APP_SUBDIRS), $(LOCAL_PATH)/$(F))

LOCAL_SRC_FILES := $(foreach F, $(APP_SUBDIRS), $(addprefix $(F)/,$(notdir $(wildcard $(LOCAL_PATH)/$(F)/*.c))))

LOCAL_STATIC_LIBRARIES :=

LOCAL_SHARED_LIBRARIES :=

LOCAL_LDLIBS := -lz

include $(BUILD_SHARED_LIBRARY)

