#define ORZ_PMAP_ANIM "comm.orz.graphics"
#define ORZ_FONT "comm.orz.font"
#define ORZ_COLOR_MAP "comm.orz.colortable"
#define ORZ_CONVERSATION_PHRASES "comm.orz.dialogue"
#define ORZ_MUSIC "comm.orz.music"
