LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := mpg123

LOCAL_C_INCLUDES := $(LOCAL_PATH) $(LOCAL_PATH)/include
LOCAL_CFLAGS := -O3 -Dlinux -DFT2_BUILD_LIBRARY=1 -DPHYSFS_NO_CDROM_SUPPORT=1 -DAL_ALEXT_PROTOTYPES=1 -DHAVE_GCC_DESTRUCTOR=1 -DREAL_IS_FLOAT
ifeq ($(TARGET_ARCH),arm)
LOCAL_CFLAGS += -DOPT_NEON
else
LOCAL_CFLAGS += -DOPT_GENERIC
endif

LOCAL_CPP_EXTENSION := .cpp

LOCAL_SRC_FILES := $(notdir $(wildcard $(LOCAL_PATH)/*.c))
ifeq ($(TARGET_ARCH),arm)
LOCAL_SRC_FILES += $(notdir $(wildcard $(LOCAL_PATH)/*.S))
endif

LOCAL_SHARED_LIBRARIES :=

LOCAL_STATIC_LIBRARIES :=

LOCAL_LDLIBS :=

include $(BUILD_SHARED_LIBRARY)

